/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stock_project3_without_lorry;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TSA10
 */
public class main_cheque extends javax.swing.JFrame {

    /**
     * Creates new form main_cheque
     */
    public main_cheque() {
        this.setResizable(false);
        initComponents();
        showCheque();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cheque_tb = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("MAIN SALES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CASH DETAILS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("CREDIT DETAILS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cheque_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "Phone No", "Date of Expaire", "Bank Name", "Cheque No", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(cheque_tb);

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Search :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(29, 29, 29)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList<User2> userList() 
    {
        ArrayList<User2>userList=new ArrayList<>();
        
          Connection con=null;
           String currentDir=System.getProperty("user.dir");
       
         try
        {
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            con=DriverManager.getConnection("jdbc:derby:"+currentDir+"\\Main_stock","root","root");
            String query="select * from SALES";
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(query);
            User2 user2;
            while(rs.next())
            {
               
               user2=new User2( rs.getString("NAME"),rs.getString("ADDRESS"),rs.getInt("PNUMBER"),rs.getString("DATE"),rs.getDouble("CASH"),rs.getDouble("CREDIT"),rs.getString("CH_DATE"),rs.getString("BANK_NAME"),rs.getString("CHECK_NUMBER"),rs.getDouble("CHAMOUNT"));
               userList.add(user2);
              
            }
            
            
        }
         catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
         return userList;
        
    }
    
    
    private void showCheque()
    {
        ArrayList<User2> list=userList();
    DefaultTableModel model=(DefaultTableModel)cheque_tb.getModel();
     Object[] row=new Object[7];
     for(int i=0;i<list.size();i++)
     {
         if(list.get(i).getCheque()>=1)
         {
         row[0]=list.get(i).getName();
         row[1]=list.get(i).getAddress();
         row[2]=list.get(i).getPhone();
         row[3]=list.get(i).getchDate();
         row[4]=list.get(i).getBank();
         row[5]=list.get(i).getchnumber();
          row[6]=list.get(i).getCheque();
         model.addRow(row);
         }
     }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           close();
            main_sales y=new main_sales();
            y.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       Connection con=null;
        PreparedStatement prepd=null;
        PreparedStatement prepd2=null;
         String currentDir=System.getProperty("user.dir");
         try
        {
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            con=DriverManager.getConnection("jdbc:derby:"+currentDir+"\\MAIN_STOCK","root","root");
             int selectedRow=cheque_tb.getSelectedRow();
         
           String cname=(cheque_tb.getModel().getValueAt(selectedRow,0).toString());
            String caddress=(cheque_tb.getModel().getValueAt(selectedRow,1).toString());
             String phone=(cheque_tb.getModel().getValueAt(selectedRow,2).toString());
             int cppnumber=Integer.parseInt(phone);
              String sadate=(cheque_tb.getModel().getValueAt(selectedRow,3).toString());
           String val6=(cheque_tb.getModel().getValueAt(selectedRow,6).toString());
           double chpass=Double.parseDouble(val6);
           
           System.out.println(cname+caddress+phone+cppnumber+sadate+chpass);
           
          // String val2=table_show.getModel().getValueAt(selectedRow,1).toString();
            prepd=(PreparedStatement) con.prepareStatement("update SALES set BANK_NAME=?,CHECK_NUMBER=?,CHAMOUNT=? where NAME=?");
          
            prepd.setString(1,"");
            prepd.setString(2,"");
           
            prepd.setDouble(3,0);
            prepd.setString(4,cname);
          
            prepd.executeUpdate();
            DefaultTableModel model=(DefaultTableModel) cheque_tb.getModel();
             model.setRowCount(0);
             showCheque();
            
            
             prepd2=(PreparedStatement) con.prepareStatement("insert into SALES(NAME,ADDRESS,PNUMBER,DATE,CASH,CREDIT,CH_DATE,BANK_NAME,CHECK_NUMBER,CHAMOUNT) values(?,?,?,?,?,?,?,?,?,?)");
           String nme=cname+"-cheque";
             prepd2.setString(1,nme);
            prepd2.setString(2,caddress);
            prepd2.setInt(3,cppnumber);
            prepd2.setString(4,sadate);
             prepd2.setDouble(5,chpass);
            prepd2.setDouble(6,0);
            prepd2.setString(7,sadate);
            prepd2.setString(8,"");
             prepd2.setString(9,"");
            prepd2.setDouble(10,0);
           
            int i=prepd2.executeUpdate();
            
            
            
            
            
           }
           catch(SQLException ex){
               JOptionPane.showMessageDialog(null,ex);
            } catch (ClassNotFoundException ex) { 
            Logger.getLogger(main_stock.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        close();
        main_cash y=new main_cash();
            y.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        close(); 
        main_credit y=new main_credit();
            y.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

     public void close()
    {
        WindowEvent winCloseEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winCloseEvent);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_cheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_cheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_cheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_cheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_cheque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable cheque_tb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
